import newId from '../../../../../common/src/utils/newId';
import { LogOperationUnion } from '../../../declarations/types';
import { iAbstractLogEventProps, iLogEvent } from '../interfaces/log-interfaces';
import { getDateWithNanoSecondTimeStamp } from '../utils/getNanoSecondTime';

export default abstract class BaseLogEvent implements iLogEvent {
  public date: Date;
  public description: string;
  public id: string;
  public operation: LogOperationUnion;
  public property: string;
  public timeStamp: bigint;

  protected abstract describe(): string;

  constructor({ operation, property }: iAbstractLogEventProps) {
    this.id = newId();
    this.operation = operation;
    this.property = property;

    // description to be generated by concrete classes
    this.description = this.describe();

    // generate time stamp and save date object
    const [date, nanoSecondTimeStamp] = getDateWithNanoSecondTimeStamp();
    this.date = date;
    this.timeStamp = nanoSecondTimeStamp;
  }
}
